name: icst_spinner_overlay
description: "ICST Spinner Overlay Flutter Package"
version: 1.0.0
publish_to: none
# homepage:

environment:
  sdk: ^3.10.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.12.0

flutter:
  assets:
    - assets/spinner_svgs/

flutter_gen:
  output: lib/src/generated
  integrations:
    image: true
    flutter_svg: true
  line_length: 100
  assets:
    outputs:
      package_parameter_enabled: true
